# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: godocconnect
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: godocapp
#   template:
#     metadata:
#       labels:
#         app: godocapp
#     spec:
#       containers:
#       - name: docapp
#         image:  shivaraj3652/godocapp
#         ports:
#         - containerPort: 8080


apiVersion: apps/v1
kind: Deployment
metadata:
  name: godocconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: godocapp
  template:
    metadata:
      labels:
        app: godocapp
    spec:
      containers:
        - name: godocapp
          image: shivaraj3652/godocapp
          env:
            - name: DB_Config
              value: host=postgres-service user=postgres password=shivaraj dbname=docapp port=5432 sslmode=disable
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: ""
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sleep", "5"]
          startupProbe:
            httpGet:
              path: /health
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: godocapp-service
spec:
  selector:
    app: godocapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080



