apiVersion: apps/v1
kind: Deployment
metadata:
  name: godoc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: godoc
  template:
    metadata:
      labels:
        app: godoc
    spec:
      containers:
        - name: godoc
          image: shivaraj3652/dockerized-docconnect-godocapp
          env:
            - name: DB_Config
              value: host=postgres-service user=postgres password=shivaraj dbname=docapp port=5432 sslmode=disable
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: ""
          ports:
            - containerPort: 8080          
---
apiVersion: v1
kind: Service
metadata:
  name: godoc-service-nodeport
spec:
  selector:
    app: godoc
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort