# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: postgres-deployment
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: postgres
#   template:
#     metadata:
#       labels:
#         app: postgres
#     spec:
#       containers:
#       - name: postgres
#         image: postgres:14.10
#         env:
#         - name: POSTGRES_DB
#           value: docapp
#         - name: POSTGRES_USER
#           value: postgres
#         - name: POSTGRES_PASSWORD
#           value: "shivaraj"
#         ports:
#         - containerPort: 5432

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14.10
        env:
        - name: POSTGRES_DB
          value: docapp
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: "shivaraj"
        ports:
        - containerPort: 5432
        command: ["/bin/sh", "-c", "apt-get update && apt-get install -y dnsutils && tail -f /dev/null"]
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432


        